### ISSUE TITLE
Setup 

### ISSUE THREAD

**Issue by LDVera** [Brightcoders-Bootcamps/kata-08-reloj-checador-team04-kata08#1]
# REQUIREMENTS
using ruby version 2.7.2
using rails version 6.0.3.4
using unicorn version 5.8.0
using sass-rails version 6 or highter
install and use unicorn  by default

# DESIGN

# Acceptance Criteria
List all required acceptance criteria
- [x] rails new command generate all the directories and archives correctly 
- [x] use ruby v2.7.2 or some highter version
- [x] use rails v6.0.3.4 or some highter version

**Comment by MiguelOcegueraM** [comment]
Esta correcto, parece que todo esta configurado correctamente.
