### ISSUE TITLE
Add company branches

### ISSUE THREAD

**Issue by LDVera** [Brightcoders-Bootcamps/kata-08-reloj-checador-team04-kata08#6]
# REQUIREMENTS
use the activeadmin 
use ruby version 2.7.2
use rails version 6.0.3.4

# DESIGN

# Acceptance Criteria
List all required acceptance criteria
- [ ] add companies and store it
- [ ] save the name of the company
- [ ] save the direction of the company

**Comment by LPMendoza** [comment]
You already have setup active admin and you can now register companies. I think you have a good advance, but you should include a screenshot of the module works.
